"""add_root_user_setup_token

Revision ID: 385974310662
Revises: c4d5e6f7a8b9
Create Date: 2026-07-12 19:46:30.470841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '385974310662'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rootusersetuptoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app_data'
    )
    op.create_index(op.f('ix_app_data_rootusersetuptoken_token_hash'), 'rootusersetuptoken', ['token_hash'], unique=False, schema='app_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_data_rootusersetuptoken_token_hash'), table_name='rootusersetuptoken', schema='app_data')
    op.drop_table('rootusersetuptoken', schema='app_data')
    # ### end Alembic commands ###
