"""init

Revision ID: 6506b30b0847
Revises:
Create Date: 2026-02-10 18:34:08.464061

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6506b30b0847"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "verification_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "db_activation_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("db_activation_token_created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "roles",
            sa.ARRAY(
                sa.Enum(
                    "ADMIN",
                    "USER",
                    "MANAGE_TEAMS",
                    "MANAGE_ATLASES_AND_MAPS",
                    "LOAD_DATA",
                    "LOAD_ICONS",
                    "WITHDBACCESS",
                    name="userrole",
                    schema="app_data",
                )
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app_data",
    )
    op.create_index(
        op.f("ix_app_data_user_email"),
        "user",
        ["email"],
        unique=True,
        schema="app_data",
    )
    op.create_index(
        op.f("ix_app_data_user_username"),
        "user",
        ["username"],
        unique=True,
        schema="app_data",
    )
    op.create_table(
        "atlas",
        sa.Column(
            "access_policy",
            sa.Enum(
                "standard", "internal", "public", name="accesspolicy", schema="app_data"
            ),
            server_default=sa.text("'standard'"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_data.user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["app_data.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app_data",
    )
    op.create_index(
        op.f("ix_app_data_atlas_name"),
        "atlas",
        ["name"],
        unique=True,
        schema="app_data",
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("INFO", "SUCCESS", "WARNING", "ERROR", name="notificationtype"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_data.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app_data",
    )
    op.create_index(
        op.f("ix_app_data_notification_is_read"),
        "notification",
        ["is_read"],
        unique=False,
        schema="app_data",
    )
    op.create_index(
        op.f("ix_app_data_notification_user_id"),
        "notification",
        ["user_id"],
        unique=False,
        schema="app_data",
    )
    op.create_table(
        "refreshtoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_data.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app_data",
    )
    op.create_index(
        op.f("ix_app_data_refreshtoken_token_hash"),
        "refreshtoken",
        ["token_hash"],
        unique=False,
        schema="app_data",
    )
    op.create_index(
        op.f("ix_app_data_refreshtoken_user_id"),
        "refreshtoken",
        ["user_id"],
        unique=False,
        schema="app_data",
    )
    op.create_table(
        "team",
        sa.Column(
            "access_policy",
            sa.Enum(
                "standard", "internal", "public", name="accesspolicy", schema="app_data"
            ),
            server_default=sa.text("'standard'"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_data.user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["app_data.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app_data",
    )
    op.create_index(
        op.f("ix_app_data_team_name"), "team", ["name"], unique=True, schema="app_data"
    )
    op.create_table(
        "atlasteamlink",
        sa.Column("atlas_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("can_manage_atlas", sa.Boolean(), nullable=False),
        sa.Column("can_create_maps", sa.Boolean(), nullable=False),
        sa.Column("can_edit_maps", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["atlas_id"], ["app_data.atlas.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["app_data.team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("atlas_id", "team_id"),
        schema="app_data",
    )
    op.create_table(
        "map",
        sa.Column(
            "access_policy",
            sa.Enum(
                "standard", "internal", "public", name="accesspolicy", schema="app_data"
            ),
            server_default=sa.text("'standard'"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("style", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("atlas_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["atlas_id"], ["app_data.atlas.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_data.user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["app_data.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("atlas_id", "name", name="uix_map_atlas_name"),
        schema="app_data",
    )
    op.create_table(
        "userteamlink",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["app_data.team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["app_data.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "team_id"),
        schema="app_data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userteamlink", schema="app_data")
    op.drop_table("map", schema="app_data")
    op.drop_table("atlasteamlink", schema="app_data")
    op.drop_index(op.f("ix_app_data_team_name"), table_name="team", schema="app_data")
    op.drop_table("team", schema="app_data")
    op.drop_index(
        op.f("ix_app_data_refreshtoken_user_id"),
        table_name="refreshtoken",
        schema="app_data",
    )
    op.drop_index(
        op.f("ix_app_data_refreshtoken_token_hash"),
        table_name="refreshtoken",
        schema="app_data",
    )
    op.drop_table("refreshtoken", schema="app_data")
    op.drop_index(
        op.f("ix_app_data_notification_user_id"),
        table_name="notification",
        schema="app_data",
    )
    op.drop_index(
        op.f("ix_app_data_notification_is_read"),
        table_name="notification",
        schema="app_data",
    )
    op.drop_table("notification", schema="app_data")
    op.drop_index(op.f("ix_app_data_atlas_name"), table_name="atlas", schema="app_data")
    op.drop_table("atlas", schema="app_data")
    op.drop_index(
        op.f("ix_app_data_user_username"), table_name="user", schema="app_data"
    )
    op.drop_index(op.f("ix_app_data_user_email"), table_name="user", schema="app_data")
    op.drop_table("user", schema="app_data")
    # ### end Alembic commands ###
    # Named Postgres ENUM types are standalone catalog objects: DROP TABLE does not
    # remove them, so they must be dropped explicitly for downgrade to be reversible.
    sa.Enum(name="userrole", schema="app_data").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="accesspolicy", schema="app_data").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="notificationtype").drop(op.get_bind(), checkfirst=True)
