"""add_password_reset_token

Revision ID: 987372104469
Revises: 6506b30b0847
Create Date: 2026-03-28 20:25:29.025031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "987372104469"
down_revision: Union[str, Sequence[str], None] = "6506b30b0847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passwordresettoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_data.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app_data",
    )
    op.create_index(
        op.f("ix_app_data_passwordresettoken_token_hash"),
        "passwordresettoken",
        ["token_hash"],
        unique=False,
        schema="app_data",
    )
    op.create_index(
        op.f("ix_app_data_passwordresettoken_user_id"),
        "passwordresettoken",
        ["user_id"],
        unique=False,
        schema="app_data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_app_data_passwordresettoken_user_id"),
        table_name="passwordresettoken",
        schema="app_data",
    )
    op.drop_index(
        op.f("ix_app_data_passwordresettoken_token_hash"),
        table_name="passwordresettoken",
        schema="app_data",
    )
    op.drop_table("passwordresettoken", schema="app_data")
    # ### end Alembic commands ###
