"""

Revision ID: a86774f9c343
Revises: a1b2c3d4e5f6
Create Date: 2026-03-31 17:34:02.128342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a86774f9c343'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('db_activation_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='app_data')
    op.drop_column('user', 'db_activation_token_hash', schema='app_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('db_activation_token_hash', sa.VARCHAR(), autoincrement=False, nullable=True), schema='app_data')
    op.drop_column('user', 'db_activation_token', schema='app_data')
    # ### end Alembic commands ###
