class AppParameter:
    MIN_PASSWORD_LENGTH = 12
    TOKEN_LENGTH = 32
    TOKEN_TYPE = "Bearer"
    REFRESH_TOKEN_COOKIE_NAME = "canopy_rt"
    REDIS_USER_CHANNEL_PREFIX = "user:"
    RESET_TOKEN_EXPIRE_MINUTES = 10
    ADMIN_SETUP_TOKEN_EXPIRE_MINUTES = 30
    PAGINATION_DEFAULT_SKIP = 0
    PAGINATION_DEFAULT_LIMIT = 25
    PAGINATION_MAX_LIMIT = 100
    WS_MAX_CONNECTIONS_PER_USER = 5
    WS_INACTIVITY_TIMEOUT_S = 300
    WS_MAX_MSG_BYTES = 256
