"""Integration tests validating the Alembic migration chain end-to-end.

Exercises `alembic upgrade head` / `downgrade base` against a dedicated, blank
PostgreSQL container (not the shared `engine` fixture from conftest.py, which
is pre-populated via `SQLModel.metadata.create_all` and would conflict with
migrations creating the same tables), and checks the resulting schema matches
SQLModel's metadata (no model/migration drift).
"""

import os
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, text
from testcontainers.core.waiting_utils import wait_for_logs
from testcontainers.postgres import PostgresContainer

API_DIR = Path(__file__).resolve().parents[2]
APP_SCHEMAS = ("app_data", "users_data")


@contextmanager
def _postgres_env(container: PostgresContainer) -> Iterator[None]:
    """Temporarily point alembic/env.py's POSTGRES_* env vars at `container`."""
    env_vars = {
        "POSTGRES_USER": container.username,
        "POSTGRES_PASSWORD": container.password,
        "POSTGRES_DB": container.dbname,
        "POSTGRES_HOST": container.get_container_host_ip(),
        "POSTGRES_PORT": str(container.get_exposed_port(5432)),
    }
    originals = {key: os.environ.get(key) for key in env_vars}
    os.environ.update(env_vars)
    try:
        yield
    finally:
        for key, value in originals.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value


def _create_app_schemas(container: PostgresContainer) -> None:
    """Pre-create app_data/users_data: env.py's version table and models need them to exist."""
    engine = create_engine(container.get_connection_url())
    with engine.begin() as conn:
        for schema in APP_SCHEMAS:
            conn.execute(text(f"CREATE SCHEMA IF NOT EXISTS {schema}"))
    engine.dispose()


@pytest.fixture(scope="module")
def migration_container() -> Iterator[PostgresContainer]:
    """A dedicated, blank Postgres instance for exercising the real migration chain."""
    postgres = PostgresContainer(
        image="postgres:16-alpine",
        username="migrator",
        password="migrator",
        dbname="migration_test",
        driver="psycopg",
    )
    with postgres:
        wait_for_logs(
            container=postgres,
            predicate="database system is ready to accept connections",
        )
        _create_app_schemas(postgres)
        yield postgres


@pytest.fixture(scope="module")
def alembic_config(migration_container: PostgresContainer) -> Iterator[Config]:
    """Alembic Config wired to the dedicated container via env.py's POSTGRES_* env vars."""
    with _postgres_env(migration_container):
        cfg = Config(str(API_DIR / "alembic.ini"))
        cfg.set_main_option("script_location", str(API_DIR / "alembic"))
        yield cfg


def test_upgrade_to_head_succeeds_on_a_blank_database(alembic_config: Config) -> None:
    """The full migration chain must apply cleanly on a fresh database."""
    command.upgrade(alembic_config, "head")


def test_downgrade_to_base_is_fully_reversible(
    alembic_config: Config, migration_container: PostgresContainer
) -> None:
    """Every migration's downgrade() must undo its upgrade(), leaving no app tables behind."""
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")

    engine = create_engine(migration_container.get_connection_url())
    with engine.connect() as conn:
        remaining = conn.execute(
            text(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = ANY(:schemas) AND table_name != 'alembic_version'"
            ),
            {"schemas": list(APP_SCHEMAS)},
        ).fetchall()
    engine.dispose()

    assert remaining == []


def test_model_metadata_matches_migrations(alembic_config: Config) -> None:
    """After upgrading to head, autogenerate must detect zero drift against SQLModel.metadata."""
    command.upgrade(alembic_config, "head")

    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"Model/migration drift detected: {exc}")
